default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: rails_5_1_base_1_0_development

test:
  <<: *default
  database: rails_5_1_base_1_0_test
